AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  dynamo-stream-processor

  Sample SAM Template for dynamo-stream-processor
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  StreamToArchive:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello-world/bin/
      Handler: app.handler
      Runtime: nodejs14.x

